Gradien/Gradien/Models/Hotels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace Gradien.Models
{
    public class Hotels:GDbContext
    {


        [Key]
        [Required]
        [Display(Name = "Hotel ID")]
        public int HOTEL_ID { get; set; }

        [Required]
        [Display(Name = "Hotel Name")]
        public string HOTEL_NAME { get; set; }

        [Required]
        [Display(Name = "Hotel State")]
        public string HOTEL_STATE { get; set; }

        [Required]
        [Display(Name = "Hotel City")]
        public string HOTEL_CITY { get; set; }

        [Display(Name = "Hotel Image")]
        public string HOTEL_IMAGE { get; set; }

        [Display(Name = "Deletion Status")]
        public bool DELETE_STAT { get; set; }

    }
}

Gradien/Gradien/Controllers/HotelController.cs
using Gradien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gradien.Controllers
{
    public class HotelController : Controller
    {
        GDbContext db = new GDbContext();


        //Take Results from Home page, displays to Search Page
        [HttpPost]
        public ActionResult Index()
        {
            string city = Request["selectLocation"].ToString();

            if (Request["txtName"].ToString() == "")
            {
                if (Request["selectLocation"].ToString() == "")
                {
                    List<Hotels> hotels = (from records in db.Hotel select records).ToList<Hotels>();
                    return View(hotels);
                }
                else
                {
                    List<Hotels> hotels = (from records in db.Hotel where records.HOTEL_CITY == city select records).ToList<Hotels>();
                    return View(hotels);
                }

            }
            else
            {
                string name = Request["txtName"].ToString();
                if (Request["selectLocation"].ToString() == "")
                {
                    List<Hotels> hotels = (from records in db.Hotel where records.HOTEL_NAME.Contains(name) select records).ToList<Hotels>();
                    return View(hotels);
                }
                else
                {
                    List<Hotels> hotels = (from records in db.Hotel where records.HOTEL_CITY == city && records.HOTEL_NAME.Contains(name) select records).ToList<Hotels>();
                    return View(hotels);
                }
            }
        }

    }
}

Gradien/Gradien/Views/Hotel/Index.cshtml
@model IEnumerable<Gradien.Models.Hotels>

@{
    ViewBag.Title = "Search";
}

<div id="searchPageContent">
    <fieldset>
        <!--Searches hotel database-->
        <h2>Search Hotels</h2>
        @using (Html.BeginForm("Index", "Hotel"))
        {
            List<SelectListItem> list = new List<SelectListItem>();
            list.Add(new SelectListItem() { Text = "All Locations", Value = "" });
            list.Add(new SelectListItem() { Text = "Chicago, Illinois", Value = "chicago" });
            list.Add(new SelectListItem() { Text = "Grand Rapids, Michigan", Value = "grand rapids" });
            list.Add(new SelectListItem() { Text = "Sydney, Australia", Value = "sydney" });

            @Html.Label("Hotel Name")<br />
            @Html.TextBox("txtName")<br />
            <br />
            @Html.Label("Hotel City")<br />
            @Html.DropDownList("selectLocation", list)<br />
            <br />
            <input type="submit" value="Search" id="btnSubmit" />
        }
    </fieldset>

    <br />

    <h2>Results</h2>
    <!--Sets column names for results table from model variables-->
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HOTEL_IMAGE)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HOTEL_NAME)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HOTEL_CITY)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HOTEL_STATE)
            </th>
        </tr>
        <!--Runs through all items given from HotelController and displays their information to the screen in a table-->
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img class="hotelImage" src="@Url.Content("~/Images/"+item.HOTEL_IMAGE)" alt="Image" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HOTEL_NAME)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HOTEL_CITY)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HOTEL_STATE)
                </td>
            </tr>
        }

    </table>
</div>