Gradien/Gradien/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gradien.Controllers
{
    public class SupportController : Controller
    {
        // Return Contact Us page
        public ActionResult Contact()
        {
            return View();
        }

        // Return Feedback page (currently not available)
        //public ActionResult Feedback()
        //{
        //    return View();
        //}
        
    }
}

Gradien/Gradien/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<!--The body rendering from the admin page starts at the content-wrapper class-->
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/AdminContent/css")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">

            <!-- Logo -->
            <a href="/Admin" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>A</b>LT</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b>LTE</span>
            </a>

            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">                           
                        </li>
                        <li class="dropdown user user-menu">
                                <span class="hidden-xs">@User.Identity.Name</span>
                            <ul class="dropdown-menu">
                                <!-- User stuff -->
                                <li class="user-header">
                                    <p>
                                        Hello @User.Identity.Name;                                        
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        @Html.ActionLink("Sign out", "Logout", "Account", null, new { @class = "btn btn-default btn-flat" })
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li>@Html.ActionLink("User List", "UserList")</li>
                    <li>@Html.ActionLink("Hotel List", "HotelList")</li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Dashboard
                    <small>Version 2.0</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li class="active">Dashboard</li>
                </ol>
            </section>

            <section class="content">
                <img src="~/Images/Logo.png" alt="Gradiens Logo" style="height:150px;width:100px;float:left;margin-right:10px;margin-left:200px" />
                <h1 id="title">Gradiens</h1>
                <h4 id="subTitle">A Travel Agency</h4>
                <br />
                <div class="headBar">
                    <ul class="headBar">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Contact Us", "Contact", "Support")</li>

                        <!--Determines if the login or logout link in navigation bar is shown to user. Based on if user is logged in or not-->
                        @if (Request.IsAuthenticated) // If user is logged in
                        {
                            <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                        }
                        @if (!Request.IsAuthenticated) // If user is not logged in
                        {
                            <li>@Html.ActionLink("Login", "Login", "Account")</li>
                        }
                    </ul>
                </div>
                <hr />
                <br />
                <div class="body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                        <div class="column">
                            <ul class="footer">
                                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                <li>@Html.ActionLink("About Us", "About", "Home")</li>
                            </ul>
                        </div>
                        <div class="column">
                            <ul class="footer">
                                <li>@Html.ActionLink("Contact Us", "Contact", "Support")</li>
                                <li>@Html.ActionLink("FAQs", "FAQ", "Home")</li>
                            </ul>
                        </div>
                        <div class="column">
                            <ul class="footer">
                                <li>@Html.ActionLink("Privacy Policy", "Privacy", "Home")</li>
                                <li>@Html.ActionLink("Terms of Service", "Terms", "Home")</li>
                            </ul>
                        </div>
                        <p style="clear:both;text-align:center;">&copy; @DateTime.Now.Year - Gradiens</p>
                    </footer>
                </div>
            </section>

        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.3.8
            </div>
            <strong>Copyright &copy; 2017 Gradiens.</strong> All rights
            reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            </ul>
            <!-- Tab panes -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/Adminbootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Gradien/Gradien/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <!--TO DO: render the Scripts and Css bundles that are currently not working: modernizr, jquery, boostrap, Css is simply a misname Content/css -> Content/Site.css-->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="header">
        <img src="~/Images/Logo.png" alt="Gradiens Logo" style="height:150px;width:100px;float:left;margin-right:10px;margin-left:200px" />
        <h1 id="title">Gradiens</h1>
        <h4 id="subTitle">A Travel Agency</h4>
        <br />
        <div id="headBar">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Contact Us", "Contact", "Support")</li>

                <!--Determines if the login or logout link in navigation bar is shown to user. Based on if user is logged in or not-->
                @if (Request.IsAuthenticated) // If user is logged in
            {
                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                }
                @if (!Request.IsAuthenticated) // If user is not logged in
            {
                    <li>@Html.ActionLink("Login", "Login", "Account")</li>
                }
            </ul>
        </div>
    </div>
    <div id="mobileHeader"class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gradiens", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <hr />
    <br />
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="col-xs-4">
                <ul class="footer">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About Us", "About", "Home")</li>
                </ul>
            </div>
            <div class="col-xs-4">
                <ul class="footer">
                    <li>@Html.ActionLink("Contact Us", "Contact", "Support")</li>
                    <li>@Html.ActionLink("FAQs", "FAQ", "Home")</li>
                </ul>
            </div>
            <div class="col-xs-4">
                <ul class="footer">
                    <li>@Html.ActionLink("Privacy Policy", "Privacy", "Home")</li>
                    <li>@Html.ActionLink("Terms of Service", "Terms", "Home")</li>
                </ul>
            </div>
            <p style="clear:both;text-align:center;">&copy; @DateTime.Now.Year - Gradiens</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>